export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const GET_ACCESS_TOKEN = 'GET_ACCESS_TOKEN';
export const EDIT_TODO = 'EDIT_TODO'
export const COMPLETE_TODO = 'COMPLETE_TODO'
export const COMPLETE_ALL_TODOS = 'COMPLETE_ALL_TODOS'
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
